[id="Using_IdM_credentials_to_log_in_to_the_WebUI-with-a-Firefox-browser_{context}"]
= Using IdM credentials to log in to the {ProjectWebUI} with a Firefox browser


This section describes how to use the Firefox browser to log in to your {ProjectWebUI} with your {FreeIPA} (IdM) login and password.

.Prerequisites
* You have enrolled your {ProjectServer} into IdM and configured the server to use IdM for authentication.
For more information, see {InstallingServerDocURL}Configuring_External_User_Groups_{project-context}#Using_FreeIPA_admin[Using {FreeIPA}] in _{InstallingServerDocTitle}_.
* An IdM server is running and reachable.
* The host on which you are using a Firefox browser to log in to the {ProjectWebUI} is an IdM client.
* You have a valid IdM login and password.
* {Team} recommends using the latest stable Firefox browser.
* Your Firefox browser is configured for Single Sign-On (SSO).

.Procedure
. Open a terminal window.
. Obtain the Kerberos ticket granting ticket (TGT) for yourself using your IdM credentials:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kinit _idm_user_
Password for idm_user@_EXAMPLE.COM_:
----
. In your browser address bar, enter the URL of your {ProjectServer}.
+
You are logged in automatically.

[NOTE]
====
Alternatively, you can skip the first two steps and enter your login and password in the fields displayed on the {ProjectWebUI}.
This is also the only option if the host from which you are accessing the {ProjectWebUI} is not an IdM client.
====
