[id="Using_IdM_credentials_to_log_in_to_the_WebUI-with-a-Chrome-browser_{context}"]
= Using IdM credentials to log in to the {ProjectWebUI} with a Chrome browser

This section describes how to use a Chrome browser to log in to your {ProjectWebUI} with your {FreeIPA} (IdM) login and password.

.Prerequisites
* Your system administrator has enrolled your {ProjectServer} into IdM and configured the server to use IdM for authentication.
For more information, see {InstallingServerDocURL}Using_FreeIPA_{project-context}[Using {FreeIPA}] in _{InstallingServerDocTitle}_.
* An IdM server is running and reachable.
* The host on which you are using the Chrome browser to log in to the {ProjectWebUI} is an IdM client.
* You have a valid IdM login and password.
* {Team} recommends using the latest stable Chrome browser.

.Procedure
. Open a terminal window.
. Enable the Chrome browser to use Kerberos authentication:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
google-chrome –auth-server-whitelist="*._example.com_" --auth-negotiate-delegate-whitelist=”*._example.com_"
----

+
[NOTE]
====
Instead of allowlisting the whole domain, you can also allowlist a specific {ProjectServer}.
====

. Obtain the Kerberos ticket-granting ticket (TGT) for yourself using your IdM credentials:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kinit _idm_user_
Password for idm_user@_EXAMPLE.COM_:
----
. In your browser address bar, enter the URL of your {ProjectServer}.
+
You are logged in automatically.


[NOTE]
====
Alternatively, you can skip the first three steps and enter your login and password in the fields displayed on the {ProjectWebUI}.
This is also the only option if the host from which you are accessing the {ProjectWebUI} is not an IdM client.
====
